/*******************************************************************************
* File Name: cycfg_platform.h
*
* Description:
* Platform configuration
* This file should not be modified. It was automatically generated by 
* ModusToolbox 1.0.0
* 
********************************************************************************
* Copyright (c) 2017-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#if !defined(CYCFG_PLATFORM_H)
#define CYCFG_PLATFORM_H

#include "cycfg_notices.h"
#include "cy_sysclk.h"
#include "cy_ble_clk.h"
#include "cy_gpio.h"
#include "cy_syspm.h"

#if defined(__cplusplus)
extern "C" {
#endif

void init_cycfg_platform(void);

#if defined(__cplusplus)
}
#endif


#endif /* CYCFG_PLATFORM_H */
