/*******************************************************************************
* File Name: cycfg_connectivity.h
*
* Description:
* Establishes all necessary connections between hardware elements.
* This file should not be modified. It was automatically generated by 
* ModusToolbox 1.0.0
* 
********************************************************************************
* Copyright (c) 2017-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#if !defined(CYCFG_CONNECTIVITY_H)
#define CYCFG_CONNECTIVITY_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "cycfg_notices.h"
void init_cycfg_connectivity(void);

#define ioss_0_port_10_pin_0_HSIOM P10_0_SCB1_UART_RX
#define ioss_0_port_10_pin_1_HSIOM P10_1_SCB1_UART_TX

#if defined(__cplusplus)
}
#endif


#endif /* CYCFG_CONNECTIVITY_H */
